### ISSUE TITLE
StableLM: tokenizer_config.json和train.py中的tokenizer不一致，导致无法训练

### ISSUE THREAD

**Issue by sharkdrop** [jiangsongtao/Med-MoE#14]
作者你好，我在尝试根据你提供的llavastablelm-1.6b-stage2 checkpoint来复现stage 3训练，但出现了以下报错 ：
![image](https://github.com/user-attachments/assets/0b90f62f-50a7-4d41-9673-0c1b746f57d4)

在llavastablelm-1.6b-stage2 checkpoint中，StableLM的tokenizer为GPT2Tokenizer，但在train.py代码中，StableLM的tokenizer被设置为Arcade100kTokenizer，请问该如何修改这个错误。

**Comment by jiangsongtao** [comment]
你好哈,只需要替换Arcade100kTokenizer.from_pretrained为transformers.AutoTokenizer.from_pretrained即可,我已经在train.py修改好了~
