### ISSUE TITLE
Reproduction of LLaVA-Med results

### ISSUE THREAD

**Issue by zihui-debug** [jiangsongtao/Med-MoE#15]
Hi! Thank you for the great job! I'm wondering how you reproduce llavamed's results on the downstream vqa task. In fact, I used the model weights([pvqa-9epoch_delta.zip](https://hanoverprod.z21.web.core.windows.net/med_llava/models/pvqa-9epoch_delta.zip), [data_RAD-9epoch_delta.zip](https://hanoverprod.z21.web.core.windows.net/med_llava/models/data_RAD-9epoch_delta.zip), [Slake1.0-9epoch_delta.zip](https://hanoverprod.z21.web.core.windows.net/med_llava/models/Slake1.0-9epoch_delta.zip)) in this repo https://github.com/microsoft/LLaVA-Med/tree/v1.0.0, but the results of the close type differ significantly from those in llavamed's paper while the open type are similar . I checked the model's responses for close type questions and found that it doesn't seem to understand that the question requires a yes or no answer. I use `simple` conv_template in this file https://github.com/microsoft/LLaVA-Med/blob/v1.0.0/llava/conversation.py.
![image](https://github.com/user-attachments/assets/9db9e10f-d4cd-4af5-b665-2abf42112ace)

Can you share your  reproducing settings? Did you add extra prompt?

**Comment by jiangsongtao** [comment]
Hello! The VQA results of LLaVA-Med are based on their paper's Table 4. However, given the situation you mentioned, you could try adding a prompt to encourage it to answer closed questions with "yes" or "no."
