### ISSUE TITLE
about the "Assistant:'

### ISSUE THREAD

**Issue by Eldo-rado** [jiangsongtao/Med-MoE#16]
Thank you for your contribution. 
I’d like to ask: when training based on the LLava weights, does the output include "Assistant:"? Like LLava, I included "Assistant:" as part of the output during training, but it never appears in my results.

**Comment by jiangsongtao** [comment]
Hello, your training data does not need to include "Assistant:". The conversation.py script will organize your training data into the appropriate format containing "User" and "Assistant" based on the version parameter used during your training.
