### ISSUE TITLE
About router training

### ISSUE THREAD

**Issue by Ian-dddd** [jiangsongtao/Med-MoE#18]
Hi! Thank you for the great work! 
Are you planning to release the code for router training?

**Comment by jiangsongtao** [comment]
Hi! Sorry for the delay. I’ve updated the Router training process, and you can find the updated version in the following notebook: [Router_Train.ipynb](https://github.com/jiangsongtao/Med-MoE/blob/main/Router_Train.ipynb). Feel free to check it out!

**Comment by Ian-dddd** [comment]
Thanks!
